# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    - name: Install dependencies
      run: |
        curl -sSL https://install.python-poetry.org | python3 - --version 1.3.2;
        poetry --version
        poetry show -v
        source $(poetry env info --path)/bin/activate
        poetry install;
        pip install cobra gurobipy flake8 pytest

    - name: Run tests
      run: |
        poetry run python3 .github/workflows/ci_test.py;

    - name: GitHub Action for Flake8
      uses: cclauss/GitHub-Action-for-Flake8@v0.5.0
